
[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = true
address = "0.0.0.0"

[theme]
base = "light"
primaryColor = "#007bff"
secondaryBackgroundColor = "#f0f0f5"
textColor = "#333333"
